version: "2.26"

services:
  app:
    container_name: app
    working_dir: /app
    image: app
    build:
      context: .
      target: dev
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"